services:
  - type: web
    name: mappu-chat-backend
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000 # Render akan override ini, tapi wajib ada
